services:
  - type: web
    name: skilltempus-ml
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        value: skill_decay_db